REBOL []

import %grammar.r

assert [[0] = scan-source "0"]
assert [[1] = scan-source "1"]
assert [[1] = scan-source "01"]
assert [[1] = scan-source "001"]
assert [[1.0] = scan-source "001.0"]
assert [[1.0%] = scan-source "001.0%"]
assert [[13:00:00] = scan-source "01:00:00PM"]
assert [[$12.32] = scan-source "$12.32"]
assert [[|] = scan-source "|"]
assert [['|] = scan-source "'|"]
assert [[+] = scan-source "+"]
assert [[-] = scan-source "-"]
assert [[<] = scan-source "<"]
assert [[<] = scan-source "< "]
assert [[>>] = scan-source ">>"]
assert [[<< >>] = scan-source "<< >>"]
assert [[< > << >> <|] = scan-source "< > << >> <|"]
assert [[a] = scan-source "a"]
assert [[a1 b+c 1 / //] = scan-source "a1 b+c +1 / // "]
assert [[a:] = scan-source "a:"]
assert [[:a] = scan-source ":a"]

assert [[[a b]] = scan-source "[a b]"]
assert [[[a b [1]]] = scan-source "[a b [1]]"]
assert [[(a b)] = scan-source "(a b)"]
assert [[(a b (1 2))] = scan-source "(a b (1 2))"]
assert [[[a b [1 (2)]]] = scan-source "[a b [1 (2)]]"]
assert [[[a b [1 (2 [3])]]] = scan-source "[a b [1 (2 [3])]]"]
